### ISSUE TITLE
Findbugs analysis fails again for package-info.java

### ISSUE THREAD

**Issue by ManfredSchenkIOSB** [SonarQubeCommunity/sonar-findbugs#36]
The fix mentioned in pull-request #1  does not work anymore in current version (3.4.3) .

**Comment by h3xstream** [comment]
Just to be sure I understand.
The only java files in the source directory are "package-info.java" which do not generate compiled classes.

I think a correct fix would be to **exclude file with the name package-info.java** to [determine if Java files need to be compile](https://github.com/SonarQubeCommunity/sonar-findbugs/blob/master/src/main/java/org/sonar/plugins/findbugs/FindbugsConfiguration.java#L138,L141).
This is obviously a shortcut because any file could be empty with no class.

**Comment by ManfredSchenkIOSB** [comment]
Yes. The only files in the source directory are "package-info.java"

**Comment by h3xstream** [comment]
ETA: Unknown (Hopefully next week)

**Comment by SenhorCastor** [comment]
I updated to this version and I think I am facing this issue (hoping). Any rough idea when the new version will be available with the fix?

**Comment by h3xstream** [comment]
Closing for tracking.. A link to the release will be add when ready.

**Comment by h3xstream** [comment]
The fix will be push to the official plugin repository soon.

A Request For Feadback period is open to get feedback to make sure the bugs are properly fixes. You can download the release candidate and ask to reopen the issue if anything is found.
https://github.com/SonarQubeCommunity/sonar-findbugs/releases/tag/3.4.4

This release was post-pone multiple times. Thank you for your patience.
